import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import BannerBar from "@/components/layout/BannerBar";
import { Providers } from "@/lib/providers";
import Header from "@/components/Header";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={montserrat.variable}>
          <BannerBar />
          <Header />
          {children}
        </body>
      </html>
    </Providers>
  );
}
